#!/bin/bash

# Ce montage utilise l'environnement Aster mais supprime la référence aux
# prérequis SALOME4 pour prendre ceux de SALOME5. Cela permet de disposer
# de Numpy 1.3.0 avec Scipy 0.7.0
# -----------------------------------------------------------------------

HERE=`pwd`

if ( ! test -d sources )
then
  mkdir sources
fi
if ( test -f recherche_xx_Fonctionnelles.ps )
then
  gzip -f recherche_xx_Fonctionnelles.ps
fi

echo
echo "===== Source de l'environnement ASTER"
cd /home/ahbhhjp/SALOME5/Aster/aster-STA94-i386
source envAster.sh > /dev/null

# Retrait du PYTHONPATH positionné par ASTER et utilisation de SALOME5
# --------------------------------------------------------------------
unset PYTHONPATH
export ROOT_SALOME=/home/ahbhhjp/SALOME5/Salome_5.Dev/SALOME5/Prerequis
FIC=$ROOT_SALOME/../V5_Dev/prerequis-debianForSalome-V5_Dev.sh
echo "===== Source de l'environnement SALOME5"
if [ -f "$FIC" ]; then
   source $FIC 
   # echo $FIC
fi
# echo $PYTHONPATH

cd $HERE
WP=`which python`
echo "===== Python utilisé.........: $WP"
echo "===== Calcul effectué dans...: $HERE"
echo
/usr/bin/time --portability python $1
