# -*- coding: utf-8 -*-
#  Copyright (C) 2010 EDF R&D
#
#  This library is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 2.1 of the License.
#
#  This library is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this library; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
#  See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

import os
import subprocess
import traceback
import SalomePyQt

class AdaoCase:

  def __init__(self):

    self.name = "not yet defined"           # Name of the case

    self.filename = "not yet defined"       # Python filename generated by Eficas
    self.yacs_filename = "not yet defined"  # Yacs schema filename

    self.salome_study_id = -1               # Study of the case
    self.salome_study_item = None           # Study item object

    self.eficas_editor = None               # Editor object from Eficas

  def isOk(self):
    if self.eficas_editor.jdc:
      return self.eficas_editor.jdc.isvalid()
    return False

  def createYACSFile(self):
    rtn = ""
    if (self.filename == ""):
      return "You need to save your case to export it"

    filename = self.filename[:self.filename.rfind(".")] + '.py'
    if not os.path.exists(filename):
      msg =  "Cannot find the py file for YACS generation \n"
      msg += "Is your case correct ? \n"
      msg += "(Try to load: " + filename + ")"
      return msg

    if not os.environ.has_key("ADAO_ROOT_DIR"):
      return "Please add ADAO_ROOT_DIR to your environnement"

    adao_path = os.environ["ADAO_ROOT_DIR"]
    adao_exe = adao_path + "/bin/salome/AdaoYacsSchemaCreator.py"
    self.yacs_filename = self.filename[:self.filename.rfind(".")] + '.xml'
    args = ["python", adao_exe, filename, self.yacs_filename]
    p = subprocess.Popen(args)
    (stdoutdata, stderrdata) = p.communicate()
    if not os.path.exists(self.yacs_filename):
      msg  = "An error occured during the execution of AdaoYacsSchemaCreator.py \n"
      msg += "See erros details in your terminal \n"
      return msg
    return rtn

  def exportCaseToYACS(self):
    rtn = ""
    rtn = self.createYACSFile()
    if rtn != "":
      return rtn

    try:
      import libYACS_Swig
      yacs_swig = libYACS_Swig.YACS_Swig()
      yacs_swig.loadSchema(self.yacs_filename)
    except:
      msg =  "Please install YACS module, error was: \n"
      msg += traceback.format_exc()
      return msg
    return rtn
