#-*-coding:iso-8859-1-*- 
study_config = {} 
study_config['StudyType'] = 'CHECKING_STUDY'
study_config['Name'] = 'Elementary gradient test'
study_config['Debug'] = '0'
study_config['Algorithm'] = 'GradientTest'
CheckingPoint_config = {}
CheckingPoint_config['Type'] = 'Vector'
CheckingPoint_config['From'] = 'String'
CheckingPoint_config['Data'] = '1 1 1'
CheckingPoint_config['Stored'] = '0'
study_config['CheckingPoint'] = CheckingPoint_config
ObservationOperator_config = {}
ObservationOperator_config['Type'] = 'Matrix'
ObservationOperator_config['From'] = 'String'
ObservationOperator_config['Data'] = '1 0 0 ; 0 1 0 ; 0 0 1'
ObservationOperator_config['Stored'] = '0'
study_config['ObservationOperator'] = ObservationOperator_config
inputvariables_config = {}
inputvariables_config['Order'] =['adao_default']
inputvariables_config['adao_default'] = -1
study_config['InputVariables'] = inputvariables_config
outputvariables_config = {}
outputvariables_config['Order'] = ['adao_default']
outputvariables_config['adao_default'] = -1
study_config['OutputVariables'] = outputvariables_config
AlgorithmParameters_config = {} 
AlgorithmParameters_config['Type'] = 'Dict'
AlgorithmParameters_config['From'] = 'String'
AlgorithmParameters_config['Data'] = '{ "SetSeed" : 1000 }'
study_config['AlgorithmParameters'] = AlgorithmParameters_config
