
#ifndef _ADAO_IDL_
#define _ADAO_IDL_

#include "SALOME_Component.idl"
#include "DSC_Engines.idl"

module ADAO
{
  interface ADAO_GUI_COMPONENT : Engines::Superv_Component
  {
   /*!
    * Test that the component is ok
    */
    void print_ping();
  };
};
#endif
