
#ifndef _ADAO_IDL_
#define _ADAO_IDL_

#include "SALOME_Component.idl"
#include "DSC_Engines.idl"

module ADAO_COMPONENT
{
  interface ADAO_ENGINE : Engines::Component, SALOMEDS::Driver
  {
   /*!
    * Test that the component is ok
    */
    void print_ping();
  };
};
#endif
